# IMPORT LIBRARIES

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from scipy.cluster.hierarchy import dendrogram, linkage
import matplotlib.pyplot as plt

# LOAD DATASETS

In [2]:
deliveries = pd.read_csv("../data/raw_data/ball_by_ball_data.csv", encoding="latin1")

In [3]:
deliveries.head()

,season_id,match_id,batter,bowler,non_striker,team_batting,team_bowling,over_number,ball_number,batter_runs,...,is_bye,is_penalty,wide_ball_runs,no_ball_runs,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,Kolkata Knight Riders,Royal Challengers Bangalore,0,0,0,...,False,False,0,0,1,0,0,NaN,False,1
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0,...,False,False,0,0,0,0,0,NaN,False,1
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,...,False,False,1,0,0,0,0,NaN,False,1
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0,...,False,False,0,0,0,0,0,NaN,False,1
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,...,False,False,0,0,0,0,0,NaN,False,1

In [4]:
deliveries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 30 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   season_id          278205 non-null  int64
 1   match_id           278205 non-null  int64
 2   batter             278205 non-null  object
 3   bowler             278205 non-null  object
 4   non_striker        278205 non-null  object
 5   team_batting       278205 non-null  object
 6   team_bowling       278205 non-null  object
 7   over_number        278205 non-null  int64
 8   ball_number        278205 non-null  int64
 9   batter_runs        278205 non-null  int64
 10  extras             278205 non-null  int64
 11  total_runs         278205 non-null  int64
 12  batsman_type       278205 non-null  object
 13  bowler_type        278205 non-null  object
 14  player_out         13823 non-null   object
 15  fielders_involved  13823 non-null   object
 16  is_wicket          278205 non-null  bool
 17  is_wide_ball       278205 non-null  bool
 18  is_no_ball         278205 non-null  bool
 19  is_leg_bye         278205 non-null  bool
 20  is_bye             278205 non-null  bool
 21  is_penalty         278205 non-null  bool
 22  wide_ball_runs     278205 non-null  int64
 23  no_ball_runs       278205 non-null  int64
 24  leg_bye_runs       278205 non-null  int64
 25  bye_runs           278205 non-null  int64
 26  penalty_runs       278205 non-null  int64
 27  wicket_kind        13823 non-null   object
 28  is_super_over      278205 non-null  bool
 29  innings            278205 non-null  int64
dtypes: bool(7), int64(13), object(10)
memory usage: 50.7+ MB

In [5]:
deliveries.columns

Index(['season_id', 'match_id', 'batter', 'bowler', 'non_striker',
       'team_batting', 'team_bowling', 'over_number', 'ball_number',
       'batter_runs', 'extras', 'total_runs', 'batsman_type', 'bowler_type',
       'player_out', 'fielders_involved', 'is_wicket', 'is_wide_ball',
       'is_no_ball', 'is_leg_bye', 'is_bye', 'is_penalty', 'wide_ball_runs',
       'no_ball_runs', 'leg_bye_runs', 'bye_runs', 'penalty_runs',
       'wicket_kind', 'is_super_over', 'innings'],
      dtype='object')

In [6]:
deliveries.shape

(278205, 30)

- <b>Total runs of each batsmans.

In [7]:
runs = deliveries.groupby('batter')['batter_runs'].sum().reset_index()

runs.rename(columns={'batter_runs': 'batsman_total_runs'}, inplace=True)

In [8]:
runs.head()

           batter  batsman_total_runs
0  A Ashish Reddy                 280
1        A Badoni                 963
2      A Chandila                   4
3        A Chopra                  53
4     A Choudhary                  25

- <b> Total balls faced by each batsman.

In [9]:
balls = deliveries.groupby('batter')['ball_number'].count().reset_index()

balls.rename(columns={'ball_number': 'balls_faced'}, inplace=True)

In [10]:
balls.head()

           batter  balls_faced
0  A Ashish Reddy          196
1        A Badoni          740
2      A Chandila            7
3        A Chopra           75
4     A Choudhary           20

- <b> Strike rate of each batsman.

In [11]:
batsman_df = runs.merge(balls, on='batter')

In [12]:
batsman_df.head()

           batter  batsman_total_runs  balls_faced
0  A Ashish Reddy                 280          196
1        A Badoni                 963          740
2      A Chandila                   4            7
3        A Chopra                  53           75
4     A Choudhary                  25           20

In [13]:
batsman_df['strike_rate'] = (batsman_df['batsman_total_runs']*100)/ batsman_df['balls_faced']

In [14]:
batsman_df.head()

           batter  batsman_total_runs  balls_faced  strike_rate
0  A Ashish Reddy                 280          196   142.857143
1        A Badoni                 963          740   130.135135
2      A Chandila                   4            7    57.142857
3        A Chopra                  53           75    70.666667
4     A Choudhary                  25           20   125.000000

- <b> Total 4's by each batsman.

In [15]:
fours = deliveries[deliveries['batter_runs'] == 4].groupby('batter').size().reset_index(name='fours')

- <b> Total 6's by each batsman.

In [16]:
sixes = deliveries[deliveries['batter_runs'] == 6].groupby('batter').size().reset_index(name='sixes')

In [17]:
print(fours.head())
print('_'*50)
print('_'*50)
print(sixes.head())

           batter  fours
0  A Ashish Reddy     16
1        A Badoni     73
2        A Chopra      7
3     A Choudhary      1
4      A Flintoff      5
__________________________________________________
__________________________________________________
           batter  sixes
0  A Ashish Reddy     15
1        A Badoni     38
2     A Choudhary      1
3      A Flintoff      2
4       A Manohar     14

In [18]:
batsman_df = batsman_df.merge(fours, on='batter', how='left')
batsman_df = batsman_df.merge(sixes, on='batter', how='left')

In [19]:
batsman_df.head()

           batter  batsman_total_runs  balls_faced  strike_rate  fours  sixes
0  A Ashish Reddy                 280          196   142.857143   16.0   15.0
1        A Badoni                 963          740   130.135135   73.0   38.0
2      A Chandila                   4            7    57.142857    NaN    NaN
3        A Chopra                  53           75    70.666667    7.0    NaN
4     A Choudhary                  25           20   125.000000    1.0    1.0

In [20]:
batsman_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 703 entries, 0 to 702
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   batter              703 non-null    object
 1   batsman_total_runs  703 non-null    int64
 2   balls_faced         703 non-null    int64
 3   strike_rate         703 non-null    float64
 4   fours               559 non-null    float64
 5   sixes               469 non-null    float64
dtypes: float64(3), int64(2), object(1)
memory usage: 33.1+ KB

In [21]:
batsman_df.fillna(0, inplace=True)

- <b> Boundary percentage.

In [22]:
batsman_df['boundary_percentage'] = ((batsman_df['fours'] * 4 + batsman_df['sixes'] * 6)/batsman_df['batsman_total_runs'])*100

In [23]:
batsman_df.head()

,batter,batsman_total_runs,balls_faced,strike_rate,fours,sixes,boundary_percentage
0,A Ashish Reddy,280,196,142.857143,16.0,15.0,55.000000
1,A Badoni,963,740,130.135135,73.0,38.0,53.997923
2,A Chandila,4,7,57.142857,0.0,0.0,0.000000
3,A Chopra,53,75,70.666667,7.0,0.0,52.830189
4,A Choudhary,25,20,125.000000,1.0,1.0,40.000000

In [24]:
batsman_df.shape

(703, 7)

- <b> Remove low matches players.

In [25]:
batsman_df = batsman_df[batsman_df['balls_faced'] >=450]

In [26]:
batsman_df.shape

(142, 7)

- <b> Select Features

In [27]:
features = batsman_df[['batsman_total_runs','balls_faced','strike_rate','fours','sixes','boundary_percentage']]

- <b>Scale Features

In [28]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled_features = scaler.fit_transform(features)

In [29]:
scaled_features

array([[-7.45252567e-01, -7.46919067e-01, -4.14664854e-02,
        -8.06090544e-01, -7.14753264e-01, -9.62130947e-01],
       [-7.38113966e-01, -7.12063642e-01, -4.46898526e-01,
        -7.99379424e-01, -6.69724442e-01, -7.26106715e-01],
       [ 1.99207639e+00,  1.58839440e+00,  1.33747594e+00,
         1.48240127e+00,  2.51231227e+00,  7.76993572e-02],
       [-2.74986950e-02, -5.40612310e-02,  1.76792831e-01,
         3.07955323e-01,  9.57655216e-02,  1.74144746e+00],
       [-9.00354895e-01, -8.66787724e-01, -7.34254609e-01,
        -1.00071301e+00, -8.49839728e-01, -1.77164754e+00],
       [ 3.52794044e-01,  6.29816334e-03,  2.43670103e+00,
        -4.10229006e-02,  2.06202406e+00,  2.55495835e+00],
       [-1.25725295e-02,  6.58074254e-02, -5.48783162e-01,
         1.40177331e-01, -1.14368978e-01,  3.67762190e-01],
       [-4.35696873e-01, -4.46822360e-01,  7.90702073e-02,
        -5.51067996e-01, -4.29570728e-01, -8.78334791e-01],
       [-9.34101009e-01, -8.76139179e-01, -1.22634454e+00,
        -9.26890698e-01, -9.84926192e-01, -1.44919445e+00],
       [ 1.89538080e+00,  2.13757988e+00, -6.68195008e-01,
         2.16022435e+00,  5.61063343e-01, -7.32216500e-01],
       [-1.26790144e-01, -1.10169964e-01, -1.50477061e-01,
        -4.23556722e-01,  1.25784736e-01, -5.93073945e-01],
       [ 1.45148962e+00,  1.59094480e+00, -4.56421300e-01,
         1.11328968e+00,  1.31154370e+00, -5.46764477e-01],
       [-8.88024585e-01, -9.45850029e-01,  1.20720958e+00,
        -9.94001895e-01, -5.34637978e-01,  5.55884017e-01],
       [-1.91686516e-01, -3.83912569e-01,  1.86319530e+00,
        -1.28267456e-01,  2.30851986e-01,  1.57119326e+00],
       [-9.41239609e-01, -9.90056909e-01,  1.11426756e+00,
        -8.59779501e-01, -8.79858942e-01,  4.47054207e-01],
       [-2.06612681e-01, -2.88697750e-01,  7.10043637e-01,
        -6.78673793e-02, -4.89609157e-01, -3.08957750e-01],
       [-7.63423551e-01, -7.65621978e-01, -3.49097145e-02,
        -7.52401586e-01, -8.04810906e-01, -7.91901654e-01],
       [ 5.00108807e-01,  5.55483638e-01, -2.87163372e-01,
         6.70355785e-01,  6.66130593e-01,  1.00359758e+00],
       [-4.61655422e-01, -3.95814421e-01, -6.92818777e-01,
        -4.77245679e-01, -6.39705228e-01, -1.06407719e+00],
       [-9.11387278e-01, -9.74754528e-01,  1.42776126e+00,
        -8.79912860e-01, -8.04810906e-01,  2.16902527e-01],
       [-5.07731846e-01, -5.47988106e-01,  4.30446456e-01,
        -4.10134483e-01, -2.94484264e-01,  1.26056658e+00],
       [ 1.87266707e+00,  1.61304824e+00,  8.54632647e-01,
         1.44213455e+00,  4.10333063e+00,  2.15369439e+00],
       [-7.40060857e-01, -7.18014569e-01, -3.91555703e-01,
        -7.85957185e-01, -7.14753264e-01, -8.48913016e-01],
       [-1.98176153e-01, -1.04219038e-01, -7.45183425e-01,
        -7.46730217e-03, -4.44580335e-01,  5.86993358e-02],
       [ 6.26656732e-01,  5.75036682e-01,  2.53002464e-01,
         1.80444049e-01,  7.86207450e-01, -7.45889502e-01],
       [ 2.89154011e+00,  2.74627461e+00,  3.54368298e-01,
         3.15347007e+00,  2.25714895e+00,  1.75577626e-01],
       [-3.57821227e-01, -3.15901984e-01, -4.17867372e-01,
        -4.90667919e-01, -2.94484264e-01, -6.53530127e-01],
       [-3.98705941e-01, -3.44806483e-01, -5.44000943e-01,
        -6.38312552e-01, -3.54522692e-01, -1.38618867e+00],
       [-5.12274592e-01, -4.40021302e-01, -7.93721386e-01,
        -6.92001509e-01, -3.84541907e-01, -8.95568728e-01],
       [-6.69323812e-01, -7.01011922e-01,  3.98488158e-01,
        -5.10801278e-01, -7.74791692e-01,  2.15102861e-01],
       [-1.96878225e-01, -8.21155974e-02, -8.89531571e-01,
         4.62216552e-02, -6.84734049e-01, -4.57673580e-01],
       [ 1.77573840e-01,  1.56771583e-01,  1.18845447e-01,
         3.48222041e-01,  4.71005700e-01,  1.40344265e+00],
       [-9.28909299e-01, -9.88356645e-01,  1.37802233e+00,
        -9.53735176e-01, -7.14753264e-01,  4.02215186e-01],
       [-9.45782355e-01, -9.51800955e-01,  2.78337790e-02,
        -8.79912860e-01, -7.44772478e-01,  1.46412055e+00],
       [-4.57761640e-01, -3.72010717e-01, -8.70050511e-01,
        -5.44356876e-01, -3.24503478e-01, -2.21084449e-01],
       [ 1.72729920e+00,  1.68871001e+00,  1.27809815e-01,
         1.65689038e+00,  1.32655331e+00, -2.82326612e-01],
       [ 1.36647537e+00,  1.61984930e+00, -8.24186049e-01,
         2.00586860e+00, -3.99551514e-01, -8.09697635e-01],
       [-8.90620439e-01, -7.88575551e-01, -1.77501619e+00,
        -6.65157030e-01, -1.15003187e+00, -3.62539980e-01],
       [-9.39941682e-01, -9.06743942e-01, -7.91027507e-01,
        -9.00046219e-01, -9.99935799e-01, -1.13498453e+00],
       [ 4.59873057e-01,  2.35833888e-01,  1.34896897e+00,
         3.01244203e-01,  1.13142841e+00,  1.04416971e+00],
       [-4.09738325e-01, -6.04946971e-01,  2.42856509e+00,
        -6.38312552e-01,  5.07367002e-02,  2.64535915e-01],
       [-7.95222773e-01, -6.64456233e-01, -1.85666834e+00,
        -7.38979347e-01, -8.19820513e-01, -3.22707803e-01],
       [ 4.19637306e-01,  2.91942621e-01,  7.38691034e-01,
         9.31994930e-02,  9.66322735e-01,  2.76921843e-01],
       [-8.29617850e-01, -8.35332828e-01,  2.13087512e-02,
        -7.65823826e-01, -6.54714835e-01,  1.06894604e+00],
       [-6.23896351e-01, -5.38636650e-01, -1.04202350e+00,
        -7.05423748e-01, -7.14753264e-01, -1.47216220e+00],
       [ 5.75388599e-01,  5.25729007e-01,  2.48868402e-01,
         6.36800187e-01,  7.26169021e-01,  6.47570748e-01],
       [-7.37465002e-01, -7.70722772e-01,  4.67120231e-01,
        -8.86623980e-01, -4.59589942e-01, -2.64480422e-01],
       [ 1.30417485e+00,  1.05196091e+00,  1.01693232e+00,
         1.44213455e+00,  1.49165898e+00,  8.32759694e-01],
       [-9.78230541e-01, -9.79855321e-01, -8.04456304e-02,
        -8.32935022e-01, -9.99935799e-01,  5.51099596e-01],
       [ 2.04830316e-01,  5.71636152e-01, -1.85053583e+00,
         4.15333237e-01, -6.24695621e-01, -1.11859864e+00],
       [-9.71740904e-01, -9.84956115e-01,  2.08460395e-01,
        -7.92668304e-01, -9.69916585e-01,  1.23983235e+00],
       [-2.83839363e-01, -3.72010717e-01,  8.26415466e-01,
        -1.34978576e-01, -1.74407407e-01,  1.02230141e+00],
       [-7.27081583e-01, -8.18330182e-01,  1.52337265e+00,
        -7.79246065e-01, -3.54522692e-01,  1.13053717e+00],
       [-5.34572437e-02,  5.22053083e-02, -7.41304629e-01,
        -4.50401201e-01, -9.93593712e-02, -1.79189585e+00],
       [ 8.60283671e-01,  7.04256794e-01,  7.30232657e-01,
         1.87155168e-01,  2.07703366e+00,  5.87520084e-01],
       [-2.75402835e-01, -1.65428564e-01, -9.13601044e-01,
         1.26660569e-02, -8.79858942e-01, -6.98630844e-01],
       [ 1.77272666e+00,  1.75842086e+00,  4.96093891e-02,
         1.83137949e+00,  1.13142841e+00, -3.27024483e-01],
       [-2.30624339e-01, -2.06234915e-01, -2.29772247e-01,
        -2.69200970e-01, -3.09493871e-01, -5.23607223e-01],
       [-2.70860089e-01, -2.58943119e-01, -1.32358165e-01,
        -5.44451399e-02, -5.49647585e-01,  4.57297560e-02],
       [ 2.02712044e+00,  1.97945527e+00,  1.45223584e-01,
         1.74413493e+00,  1.83687995e+00, -3.24466894e-01],
       [-5.86256456e-01, -5.15683078e-01, -8.46431493e-01,
        -6.11468073e-01, -6.84734049e-01, -1.01302314e+00],
       [-7.20591945e-01, -7.31616686e-01,  1.02287452e-01,
        -6.85290389e-01, -6.84734049e-01, -5.43687957e-02],
       [ 1.33860192e-02,  9.81124533e-02, -5.78413381e-01,
        -4.10229006e-02, -3.24503478e-01, -1.09127818e+00],
       [-6.69972775e-01, -6.29600808e-01, -5.82881843e-01,
        -5.64490235e-01, -6.24695621e-01,  5.94807354e-01],
       [-7.10208526e-01, -6.55954910e-01, -7.93857668e-01,
        -8.53068381e-01, -5.94676406e-01, -1.09104052e+00],
       [-6.88143760e-01, -7.81774492e-01,  1.47033756e+00,
        -8.26223903e-01, -1.59397800e-01,  1.25079006e+00],
       [-1.03663728e+00, -9.62852675e-01, -1.86361523e+00,
        -1.00742413e+00, -1.13502226e+00, -2.23060813e+00],
       [-8.95163185e-01, -9.36498573e-01,  8.14587858e-01,
        -9.87290775e-01, -5.34637978e-01,  7.73065681e-01],
       [ 3.29431350e-01,  5.01075170e-01, -9.02758879e-01,
         3.61644280e-01,  8.07559144e-02, -3.07397055e-01],
       [-6.67376921e-01, -6.42352793e-01, -3.88545050e-01,
        -5.98045834e-01, -6.39705228e-01,  2.16865138e-01],
       [ 4.23531089e-01,  4.48366967e-01, -1.41446325e-01,
         5.49555631e-01,  2.15842379e-01,  1.12448328e-01],
       [-7.21240909e-01, -6.95060996e-01, -4.37027626e-01,
        -7.12134868e-01, -8.64849335e-01, -1.30537190e+00],
       [-8.72033570e-02,  2.50010743e-02, -8.01875213e-01,
         3.27994159e-02, -5.04618764e-01, -6.98141575e-01],
       [ 1.19385102e+00,  1.47617694e+00, -9.66273645e-01,
         9.85778410e-01,  4.55996093e-01, -1.24275363e+00],
       [-2.70211125e-01, -1.10169964e-01, -1.26005505e+00,
        -2.49067611e-01, -6.84734049e-01, -1.39505665e+00],
       [-6.51801791e-01, -6.62755968e-01,  9.36709087e-02,
        -4.83956799e-01, -6.24695621e-01,  9.80590033e-01],
       [-6.12863968e-01, -6.40652528e-01,  3.15741300e-01,
        -6.58445911e-01, -2.79474657e-01,  9.00347640e-01],
       [-5.54041349e-02, -1.37374198e-01,  6.25207883e-01,
        -2.35645371e-01,  3.05900021e-01,  2.67228328e-01],
       [-5.31743504e-01, -5.82843531e-01,  5.82235200e-01,
        -5.98045834e-01, -1.59397800e-01,  9.02986857e-01],
       [-8.52331580e-01, -7.49469464e-01, -1.67556179e+00,
        -6.71868150e-01, -9.39897371e-01,  4.56660653e-01],
       [ 2.15950903e+00,  2.11037564e+00,  1.44760807e-01,
         1.22066760e+00,  2.67741795e+00, -5.75124196e-01],
       [-2.63072524e-01, -1.70529358e-01, -7.75956165e-01,
        -1.14845217e-01, -7.14753264e-01, -8.71552517e-01],
       [ 1.17869178e-01, -1.57777373e-01,  2.19222775e+00,
        -2.35645371e-01,  1.22148606e+00,  1.50882996e+00],
       [ 4.81288860e-01,  4.56868290e-01,  1.22497531e-01,
         4.55599955e-01,  8.31236271e-01,  7.91078278e-01],
       [-9.03599714e-01, -9.32247912e-01,  5.27021284e-01,
        -8.93335099e-01, -6.99743656e-01,  7.45106981e-01],
       [-3.61715010e-01, -2.19837032e-01, -1.22791509e+00,
        -4.83956799e-01, -9.93593712e-02,  1.32816784e-01],
       [-4.90858789e-01, -6.07497368e-01,  1.43533018e+00,
        -3.49734406e-01, -2.19436228e-01,  1.76682330e+00],
       [ 4.78044041e-01,  7.00006132e-01, -1.05140960e+00,
         1.15355640e+00, -5.49647585e-01,  1.24187820e-01],
       [-6.84898941e-01, -8.46384548e-01,  2.90156959e+00,
        -4.77245679e-01, -4.44580335e-01,  2.47788623e+00],
       [-9.65251267e-01, -8.82940238e-01, -1.72718929e+00,
        -9.20179578e-01, -9.84926192e-01, -8.00341336e-01],
       [-1.42365273e-01, -2.52992193e-01,  9.37098720e-01,
         3.01244203e-01, -3.69532300e-01,  1.28000143e+00],
       [ 7.79163206e-01,  7.77368173e-01,  4.80237202e-03,
         8.85111615e-01,  7.26169021e-01,  4.01808421e-01],
       [-8.29617850e-01, -7.57120655e-01, -1.21607552e+00,
        -8.66490621e-01, -8.49839728e-01, -1.30241628e+00],
       [ 4.06424954e-02,  2.54536799e-01, -1.29650366e+00,
         5.09288913e-01, -8.64849335e-01, -5.00674942e-01],
       [-3.51331590e-01, -3.93264024e-01,  3.83012985e-01,
        -5.44356876e-01,  2.07174859e-02,  1.52295093e-01],
       [-6.48556973e-01, -6.52554380e-01, -1.49575408e-03,
        -6.92001509e-01, -4.74599549e-01,  1.13267987e-01],
       [ 7.45417093e-01,  8.40277964e-01, -4.21776696e-01,
         3.14666442e-01,  4.71005700e-01, -1.39389095e+00],
       [ 1.16571250e-01,  7.51588808e-02,  2.63318672e-01,
         2.40844126e-01, -9.30172836e-03,  2.18157423e-01],
       [ 2.53502595e-01,  2.07779522e-01,  2.69856219e-01,
         2.54266365e-01,  1.40794343e-01, -1.44179726e-01],
       [ 3.20369166e+00,  3.27845744e+00, -1.46467826e-01,
         2.99911431e+00,  3.26279263e+00,  2.00028744e-01],
       [-6.56993501e-01, -7.01862055e-01,  5.90429772e-01,
        -7.12134868e-01, -4.44580335e-01,  2.17418355e-01],
       [-6.49205936e-01, -7.30766553e-01,  1.17273599e+00,
        -7.85957185e-01, -2.64465050e-01,  4.81944237e-01],
       [ 9.43999990e-01,  7.52714335e-01,  8.76343347e-01,
         8.58267136e-01,  1.26651488e+00,  5.56921294e-01],
       [-1.02560489e+00, -9.78155057e-01, -1.28795864e+00,
        -1.03426861e+00, -1.04496462e+00, -1.89831500e+00],
       [ 1.84476163e+00,  1.96245262e+00, -3.39218609e-01,
         1.93204628e+00,  1.44663016e+00,  2.29897944e-02],
       [-4.35047910e-01, -3.17602248e-01, -1.11740223e+00,
        -2.62489850e-01, -8.64849335e-01, -9.03623684e-01],
       [ 3.02263078e+00,  3.28525850e+00, -5.40914333e-01,
         3.85813763e+00,  1.01135156e+00, -2.53974388e-01],
       [-1.63781076e-01, -2.14736238e-01,  4.03767962e-01,
        -5.71201355e-01,  5.46053736e-01,  2.71226493e-01],
       [ 1.42747796e+00,  1.14122480e+00,  1.11411741e+00,
         1.75084605e+00,  1.23649566e+00,  6.85266525e-01],
       [-4.94752572e-01, -2.48741531e-01, -2.16465081e+00,
        -3.76578884e-01, -6.54714835e-01, -2.02730474e-01],
       [ 2.45066066e-01,  2.50286138e-01, -4.33623531e-02,
         5.09288913e-01, -1.14368978e-01,  1.88009538e-01],
       [ 2.22245851e+00,  2.17498570e+00,  1.37967036e-01,
         2.09982428e+00,  1.77684152e+00, -2.93291061e-01],
       [-7.23187800e-01, -7.29066289e-01,  2.40736008e-02,
        -7.25557108e-01, -6.69724442e-01, -2.78145498e-01],
       [-9.90560852e-01, -9.88356645e-01, -1.79445265e-01,
        -8.73201740e-01, -1.07498383e+00, -4.70016115e-01],
       [-4.04546615e-01, -4.95279902e-01,  9.67339555e-01,
        -6.65157030e-01,  1.10775129e-01,  2.93342975e-01],
       [-2.15049209e-01, -4.03465612e-01,  1.86182898e+00,
        -2.76006612e-02,  4.55996093e-01,  2.98499599e+00],
       [ 2.48959849e-01,  3.23397517e-01, -4.39385422e-01,
         2.20710767e-01, -3.84541907e-01, -1.43973504e+00],
       [ 1.44476690e-01,  3.61653471e-01, -1.23365945e+00,
         6.90489144e-01, -8.49839728e-01, -3.63021314e-01],
       [ 1.14777460e+00,  1.08256567e+00,  2.59666041e-01,
         1.23408984e+00,  1.56670702e+00,  1.07755565e+00],
       [ 1.05367486e+00,  1.09361739e+00, -1.58366756e-01,
         8.18000418e-01,  9.96341949e-01, -3.67425150e-01],
       [-4.00652833e-01, -2.78496162e-01, -1.11880224e+00,
        -5.51067996e-01, -5.34637978e-01, -1.56314054e+00],
       [-8.71800492e-01, -8.88891164e-01,  2.49813234e-01,
        -7.32268227e-01, -6.99743656e-01,  1.93229699e+00],
       [-7.99116555e-01, -7.80924360e-01, -3.71962313e-01,
        -8.53068381e-01, -7.59782085e-01, -9.81352884e-01],
       [ 1.68252070e+00,  1.57819281e+00,  3.49652603e-01,
         1.24751208e+00,  2.00198563e+00, -7.98615816e-02],
       [-1.01651940e+00, -9.72204131e-01, -1.19261892e+00,
        -1.10137981e+00, -9.09878156e-01, -1.70511592e+00],
       [-8.54278471e-01, -8.10678991e-01, -8.32879039e-01,
        -8.06090544e-01, -9.69916585e-01, -1.16529184e+00],
       [-8.68555673e-01, -9.42449500e-01,  1.56086807e+00,
        -9.20179578e-01, -6.39705228e-01,  2.34031948e-01],
       [ 1.13868911e+00,  1.06131237e+00,  3.10619650e-01,
         1.20053424e+00,  5.01024914e-01, -5.38409025e-01],
       [-8.21181322e-01, -9.30547647e-01,  2.29961264e+00,
        -9.33601817e-01, -3.84541907e-01,  1.05432155e+00],
       [-9.31505154e-01, -8.76989311e-01, -1.16084675e+00,
        -9.26890698e-01, -8.94868549e-01, -7.29759024e-01],
       [-6.21949460e-01, -4.85928447e-01, -1.53745554e+00,
        -3.56445525e-01, -9.24887763e-01,  4.84706531e-02],
       [-6.26492206e-01, -7.75823566e-01,  2.36484421e+00,
        -4.50401201e-01, -4.59589942e-01,  1.72561854e+00],
       [-3.97408014e-01, -4.50222890e-01,  5.20274773e-01,
        -5.37645757e-01, -1.74407407e-01, -1.35455014e-01],
       [ 4.25695977e+00,  4.32156979e+00, -9.79723098e-02,
         3.89840435e+00,  3.09768695e+00, -6.88362022e-01],
       [ 4.00168395e-01,  1.82275552e-01,  1.35591271e+00,
         9.45511692e-01,  3.05900021e-01,  1.65584033e+00],
       [-5.70032363e-01, -5.38636650e-01, -4.12079244e-01,
        -7.05423748e-01, -5.64657192e-01, -1.26158215e+00],
       [-4.17525889e-01, -4.34920508e-01,  1.43599862e-01,
        -3.83290004e-01, -3.09493871e-01,  4.15751514e-01],
       [ 5.33854921e-01,  6.37096341e-01, -5.07443953e-01,
         6.90489144e-01,  2.07174859e-02, -3.68389133e-01],
       [-7.30975365e-01, -6.40652528e-01, -1.25721095e+00,
        -7.79246065e-01, -7.29762871e-01, -9.89444607e-01],
       [ 3.54507856e-02, -1.39924595e-01,  1.36647635e+00,
         4.42177716e-01,  9.57655216e-02,  1.80291421e+00],
       [ 7.20756471e-01,  6.08191842e-01,  5.49957840e-01,
         4.69022195e-01,  1.13142841e+00,  2.73745327e-01],
       [ 4.17041452e-01,  5.00225038e-01, -4.41451035e-01,
         1.67021809e-01,  9.51313128e-01,  4.87455246e-01]])

- <b> K-Means Clustering

In [30]:
from sklearn.cluster import KMeans, AgglomerativeClustering

In [31]:
kmeans = KMeans(
    n_clusters=4,
    random_state=42
)

batsman_df['kmeans_cluster'] = kmeans.fit_predict(scaled_features)

In [32]:
hierarchical = AgglomerativeClustering(
    n_clusters=4
)

batsman_df['hierarchical_cluster'] = hierarchical.fit_predict(scaled_features)

- <b> Save Model

In [33]:
import joblib

In [34]:
joblib.dump(kmeans, "../models/kmeans_model.pkl")
joblib.dump(hierarchical, "../models/hierarchical_model.pkl")
joblib.dump(scaler, "../models/clustering_scaler.pkl")

['../models/clustering_scaler.pkl']

- <b> Cluster labelling

In [35]:
cluster_names = {
    0: "Anchor Batter",
    1: "Aggressive Finisher",
    2: "Power Hitter",
    3: "Balanced Batter"
}

batsman_df['batsman_type'] = batsman_df['kmeans_cluster'].map(cluster_names)

- <b> Save Player Data

In [36]:
batsman_df.to_csv("../models/batsman_clusters.csv", index=False)

In [37]:
batsman_clusters = pd.read_csv("../models/batsman_clusters.csv")

In [38]:
batsman_clusters

,batter,batsman_total_runs,balls_faced,strike_rate,fours,sixes,boundary_percentage,kmeans_cluster,hierarchical_cluster,batsman_type
0,A Badoni,963,740,130.135135,73.0,38.0,53.997923,0,2,Anchor Batter
1,A Symonds,974,781,124.711908,74.0,41.0,55.646817,0,2,Anchor Batter
2,AB de Villiers,5181,3487,148.580442,414.0,253.0,61.262305,2,1,Power Hitter
3,AC Gilchrist,2069,1555,133.054662,239.0,92.0,72.885452,1,0,Aggressive Finisher
4,AD Mathews,724,599,120.868114,44.0,29.0,48.342541,0,2,Anchor Batter
...,...,...,...,...,...,...,...,...,...,...
137,WP Saha,2934,2368,123.902027,296.0,87.0,58.145876,1,2,Aggressive Finisher
138,Y Venugopal Rao,985,865,113.872832,77.0,37.0,53.807107,0,2,Anchor Batter
139,YBK Jaiswal,2166,1454,148.968363,259.0,92.0,73.314866,3,0,Balanced Batter
140,YK Pathan,3222,2334,138.046272,263.0,161.0,62.631906,1,3,Aggressive Finisher
141,Yuvraj Singh,2754,2207,124.784776,218.0,149.0,64.124909,1,3,Aggressive Finisher