## IMPORT OF LIBRARIES

In [1]:
import numpy as np
import pandas as pd


import warnings
warnings.filterwarnings('ignore')

## LOAD OF DATASETS

In [2]:
matches = pd.read_csv("../data/raw_data/ipl_matches_data.csv", encoding="latin1")
deliveries = pd.read_csv("../data/raw_data/ball_by_ball_data.csv", encoding="latin1")

## BASIC INFORMATIONS ABOUT DATASETS

In [3]:
matches.head()

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,toss_winner,team1,team2,toss_decision,match_winner,win_by_runs,win_by_wickets,player_of_match,result,stage
0,335982,2008,6,Bangalore,18-04-2008,Indian Premier League,1.0,male,T20,T20,...,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,field,Kolkata Knight Riders,140.0,NaN,46.0,win,NaN
1,1082591,2017,6,Hyderabad,05-04-2017,Indian Premier League,1.0,male,T20,T20,...,Royal Challengers Bangalore,Sunrisers Hyderabad,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35.0,NaN,15.0,win,NaN
2,1082592,2017,6,Pune,06-04-2017,Indian Premier League,2.0,male,T20,T20,...,Rising Pune Supergiant,Rising Pune Supergiant,Mumbai Indians,field,Rising Pune Supergiant,NaN,7.0,36.0,win,NaN
3,1082593,2017,6,Rajkot,07-04-2017,Indian Premier League,3.0,male,T20,T20,...,Kolkata Knight Riders,Gujarat Lions,Kolkata Knight Riders,field,Kolkata Knight Riders,NaN,10.0,57.0,win,NaN
4,1082594,2017,6,Indore,08-04-2017,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,Punjab Kings,Rising Pune Supergiant,field,Punjab Kings,NaN,6.0,71.0,win,NaN

In [4]:
matches.shape

(1169, 24)

In [5]:
matches.columns

Index(['match_id', 'season_id', 'balls_per_over', 'city', 'match_date',
       'event_name', 'match_number', 'gender', 'match_type', 'format', 'overs',
       'season', 'team_type', 'venue', 'toss_winner', 'team1', 'team2',
       'toss_decision', 'match_winner', 'win_by_runs', 'win_by_wickets',
       'player_of_match', 'result', 'stage'],
      dtype='object')

In [6]:
deliveries.head()

,season_id,match_id,batter,bowler,non_striker,team_batting,team_bowling,over_number,ball_number,batter_runs,...,is_bye,is_penalty,wide_ball_runs,no_ball_runs,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,Kolkata Knight Riders,Royal Challengers Bangalore,0,0,0,...,False,False,0,0,1,0,0,NaN,False,1
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0,...,False,False,0,0,0,0,0,NaN,False,1
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,...,False,False,1,0,0,0,0,NaN,False,1
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0,...,False,False,0,0,0,0,0,NaN,False,1
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,...,False,False,0,0,0,0,0,NaN,False,1

In [7]:
deliveries.columns

Index(['season_id', 'match_id', 'batter', 'bowler', 'non_striker',
       'team_batting', 'team_bowling', 'over_number', 'ball_number',
       'batter_runs', 'extras', 'total_runs', 'batsman_type', 'bowler_type',
       'player_out', 'fielders_involved', 'is_wicket', 'is_wide_ball',
       'is_no_ball', 'is_leg_bye', 'is_bye', 'is_penalty', 'wide_ball_runs',
       'no_ball_runs', 'leg_bye_runs', 'bye_runs', 'penalty_runs',
       'wicket_kind', 'is_super_over', 'innings'],
      dtype='object')

In [8]:
deliveries.shape

(278205, 30)

### <b>MERGE DELIVERIES WITH MATCHES DATASET

In [9]:
delivery_df = deliveries.merge(
    matches[['match_id', 'venue']],
    left_on='match_id',
    right_on='match_id',
    how='left'
)

In [10]:
delivery_df

,season_id,match_id,batter,bowler,non_striker,team_batting,team_bowling,over_number,ball_number,batter_runs,...,is_penalty,wide_ball_runs,no_ball_runs,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings,venue
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,Kolkata Knight Riders,Royal Challengers Bangalore,0,0,0,...,False,0,0,1,0,0,NaN,False,1,M Chinnaswamy Stadium
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0,...,False,0,0,0,0,0,NaN,False,1,M Chinnaswamy Stadium
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,...,False,1,0,0,0,0,NaN,False,1,M Chinnaswamy Stadium
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0,...,False,0,0,0,0,0,NaN,False,1,M Chinnaswamy Stadium
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,...,False,0,0,0,0,0,NaN,False,1,M Chinnaswamy Stadium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278200,2025,1485779,T Stubbs,Arshdeep Singh,Sameer Rizvi,Delhi Capitals,Punjab Kings,18,5,4,...,False,0,0,0,0,0,NaN,False,2,"Sawai Mansingh Stadium, Jaipur"
278201,2025,1485779,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,19,0,0,...,False,1,0,0,0,0,NaN,False,2,"Sawai Mansingh Stadium, Jaipur"
278202,2025,1485779,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,19,1,1,...,False,0,0,0,0,0,NaN,False,2,"Sawai Mansingh Stadium, Jaipur"
278203,2025,1485779,T Stubbs,MP Stoinis,Sameer Rizvi,Delhi Capitals,Punjab Kings,19,2,1,...,False,0,0,0,0,0,NaN,False,2,"Sawai Mansingh Stadium, Jaipur"
278204,2025,1485779,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,19,3,6,...,False,0,0,0,0,0,NaN,False,2,"Sawai Mansingh Stadium, Jaipur"

In [11]:
delivery_df.shape

(278205, 31)

- <b> FILTER 1st INNINGS DATA.

In [12]:
delivery_df = delivery_df[delivery_df['innings'] == 1]

- <b> CURRENT SCORE AT ANY POINT OF INNING

In [13]:
delivery_df['current_score'] = delivery_df.groupby('match_id')['total_runs'].cumsum()

- <b> WICKETS FALLEN AT ANY POINT OF INNING

In [14]:
delivery_df['is_wicket'] = delivery_df['player_out'].notnull().astype(int)

delivery_df['wickets_fallen'] = delivery_df.groupby('match_id')['is_wicket'].cumsum()

- <B>OVERS COMPLETED

In [15]:
delivery_df['overs_completed'] = delivery_df['over_number'] + (delivery_df['ball_number'] / 10)

- <b> RUN RATE

In [16]:
delivery_df['run_rate'] = delivery_df['current_score'] / delivery_df['overs_completed'].replace(0,1)

- <b>TOTAL SCORE

In [17]:
final_scores = delivery_df.groupby('match_id')['total_runs'].sum().reset_index()
final_scores.rename(columns={'total_runs': 'final_score'}, inplace=True)

In [18]:
delivery_df

,season_id,match_id,batter,bowler,non_striker,team_batting,team_bowling,over_number,ball_number,batter_runs,...,bye_runs,penalty_runs,wicket_kind,is_super_over,innings,venue,current_score,wickets_fallen,overs_completed,run_rate
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,Kolkata Knight Riders,Royal Challengers Bangalore,0,0,0,...,0,0,NaN,False,1,M Chinnaswamy Stadium,1,0,0.0,1.000000
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0,...,0,0,NaN,False,1,M Chinnaswamy Stadium,1,0,0.1,10.000000
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,...,0,0,NaN,False,1,M Chinnaswamy Stadium,2,0,0.2,10.000000
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0,...,0,0,NaN,False,1,M Chinnaswamy Stadium,2,0,0.3,6.666667
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,...,0,0,NaN,False,1,M Chinnaswamy Stadium,2,0,0.4,5.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278079,2025,1485779,M Jansen,Mustafizur Rahman,MP Stoinis,Punjab Kings,Delhi Capitals,19,1,0,...,0,0,NaN,False,1,"Sawai Mansingh Stadium, Jaipur",197,7,19.1,10.314136
278080,2025,1485779,M Jansen,Mustafizur Rahman,MP Stoinis,Punjab Kings,Delhi Capitals,19,2,0,...,0,0,caught,False,1,"Sawai Mansingh Stadium, Jaipur",197,8,19.2,10.260417
278081,2025,1485779,Harpreet Brar,Mustafizur Rahman,MP Stoinis,Punjab Kings,Delhi Capitals,19,3,6,...,0,0,NaN,False,1,"Sawai Mansingh Stadium, Jaipur",203,8,19.3,10.518135
278082,2025,1485779,Harpreet Brar,Mustafizur Rahman,MP Stoinis,Punjab Kings,Delhi Capitals,19,4,1,...,0,0,NaN,False,1,"Sawai Mansingh Stadium, Jaipur",204,8,19.4,10.515464
278083,2025,1485779,MP Stoinis,Mustafizur Rahman,Harpreet Brar,Punjab Kings,Delhi Capitals,19,5,2,...,0,0,NaN,False,1,"Sawai Mansingh Stadium, Jaipur",206,8,19.5,10.564103

In [19]:
delivery_df = delivery_df.merge(final_scores, on='match_id')

In [20]:
delivery_df

,season_id,match_id,batter,bowler,non_striker,team_batting,team_bowling,over_number,ball_number,batter_runs,...,penalty_runs,wicket_kind,is_super_over,innings,venue,current_score,wickets_fallen,overs_completed,run_rate,final_score
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,Kolkata Knight Riders,Royal Challengers Bangalore,0,0,0,...,0,NaN,False,1,M Chinnaswamy Stadium,1,0,0.0,1.000000,222
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0,...,0,NaN,False,1,M Chinnaswamy Stadium,1,0,0.1,10.000000,222
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,...,0,NaN,False,1,M Chinnaswamy Stadium,2,0,0.2,10.000000,222
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0,...,0,NaN,False,1,M Chinnaswamy Stadium,2,0,0.3,6.666667,222
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,...,0,NaN,False,1,M Chinnaswamy Stadium,2,0,0.4,5.000000,222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144126,2025,1485779,M Jansen,Mustafizur Rahman,MP Stoinis,Punjab Kings,Delhi Capitals,19,1,0,...,0,NaN,False,1,"Sawai Mansingh Stadium, Jaipur",197,7,19.1,10.314136,206
144127,2025,1485779,M Jansen,Mustafizur Rahman,MP Stoinis,Punjab Kings,Delhi Capitals,19,2,0,...,0,caught,False,1,"Sawai Mansingh Stadium, Jaipur",197,8,19.2,10.260417,206
144128,2025,1485779,Harpreet Brar,Mustafizur Rahman,MP Stoinis,Punjab Kings,Delhi Capitals,19,3,6,...,0,NaN,False,1,"Sawai Mansingh Stadium, Jaipur",203,8,19.3,10.518135,206
144129,2025,1485779,Harpreet Brar,Mustafizur Rahman,MP Stoinis,Punjab Kings,Delhi Capitals,19,4,1,...,0,NaN,False,1,"Sawai Mansingh Stadium, Jaipur",204,8,19.4,10.515464,206
144130,2025,1485779,MP Stoinis,Mustafizur Rahman,Harpreet Brar,Punjab Kings,Delhi Capitals,19,5,2,...,0,NaN,False,1,"Sawai Mansingh Stadium, Jaipur",206,8,19.5,10.564103,206

In [21]:
final_df = delivery_df[['team_batting', 'team_bowling', 'venue', 'overs_completed', 'current_score', 'wickets_fallen', 'run_rate', 'final_score']]

- <b> REMOVE EARLY NOISE

In [22]:
final_df = final_df[final_df['overs_completed'] >= 5]

# MODEL DEVELOPMENT

In [23]:
final_df.head()

,team_batting,team_bowling,venue,overs_completed,current_score,wickets_fallen,run_rate,final_score
32,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,5.0,61,0,12.200000,222
33,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,5.1,61,1,11.960784,222
34,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,5.2,61,1,11.730769,222
35,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,5.3,61,1,11.509434,222
36,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,5.4,61,1,11.296296,222

In [24]:
X = final_df.drop('final_score', axis=1)
y = final_df['final_score']

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [28]:
categorical_cols = ['team_batting', 'team_bowling', 'venue']

preprocessor = ColumnTransformer(transformers=[('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)], remainder='passthrough')

In [29]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

In [30]:
pipeline = Pipeline([('preprocessor', preprocessor),('model', LinearRegression())])

In [31]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['team_batting',
                                                   'team_bowling',
                                                   'venue'])])),
                ('model', LinearRegression())])

In [32]:
y_pred = pipeline.predict(X_test)

In [33]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("MAE:", mean_absolute_error(y_test, y_pred))
print('-'*25)
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print('-'*25)
print("R2 Score:", r2_score(y_test, y_pred))

MAE: 13.286158895700826
-------------------------
RMSE: 18.011982805006557
-------------------------
R2 Score: 0.6877704958375885

In [34]:
sample = pd.DataFrame({
    'team_batting': ['Chennai Super Kings'],
    'team_bowling': ['Mumbai Indians'],
    'venue': ['Wankhede Stadium'],
    'overs_completed': [15.3],
    'current_score': [132],
    'wickets_fallen': [4],
    'run_rate': [8.62]
})

In [35]:
prediction = pipeline.predict(sample)

print("Predicted Score:", round(prediction[0]))

Predicted Score: 176

In [36]:
import joblib

joblib.dump(pipeline, '../models/score_prediction.pkl')

['../models/score_prediction.pkl']